//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVPlot {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVPlot.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Normal dialogue, Speaker: {0}, Content: {1} 的本地化字符串。
        /// </summary>
        public static string ByteString2StringType1 {
            get {
                return ResourceManager.GetString("ByteString2StringType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Narrator dialogue, Content: {0} 的本地化字符串。
        /// </summary>
        public static string ByteString2StringType2 {
            get {
                return ResourceManager.GetString("ByteString2StringType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play bubble: {0} 的本地化字符串。
        /// </summary>
        public static string ByteString2StringType3 {
            get {
                return ResourceManager.GetString("ByteString2StringType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play sound effect: {0} 的本地化字符串。
        /// </summary>
        public static string ByteString2StringType4 {
            get {
                return ResourceManager.GetString("ByteString2StringType4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shake screen, Intensity: {0}, Speed: {1}, Duration: {2} frames 的本地化字符串。
        /// </summary>
        public static string ByteString2StringType5 {
            get {
                return ResourceManager.GetString("ByteString2StringType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play BGM: {0} 的本地化字符串。
        /// </summary>
        public static string ByteString2StringType6 {
            get {
                return ResourceManager.GetString("ByteString2StringType6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Plot 的本地化字符串。
        /// </summary>
        public static string CreatePlot_DefaultName {
            get {
                return ResourceManager.GetString("CreatePlot_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter new plot ID (Cannot modify) 的本地化字符串。
        /// </summary>
        public static string CreatePlot_PlotID_Title {
            get {
                return ResourceManager.GetString("CreatePlot_PlotID_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter ID 的本地化字符串。
        /// </summary>
        public static string CreatePlot_PlotID_WindowTitle {
            get {
                return ResourceManager.GetString("CreatePlot_PlotID_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate Plot ID! 的本地化字符串。
        /// </summary>
        public static string CreatePlot_PlotIDDuplicate {
            get {
                return ResourceManager.GetString("CreatePlot_PlotIDDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Plot ID! Make sure that ID only has English characters, numbers and &apos;_&apos; 的本地化字符串。
        /// </summary>
        public static string CreatePlot_PlotIDInvalid {
            get {
                return ResourceManager.GetString("CreatePlot_PlotIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter new plot name (Cannot modify) 的本地化字符串。
        /// </summary>
        public static string CreatePlot_PlotName_Title {
            get {
                return ResourceManager.GetString("CreatePlot_PlotName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter name 的本地化字符串。
        /// </summary>
        public static string CreatePlot_PlotName_WindowTitle {
            get {
                return ResourceManager.GetString("CreatePlot_PlotName_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NewPlotProject 的本地化字符串。
        /// </summary>
        public static string CreatePlotProject_DefaultName {
            get {
                return ResourceManager.GetString("CreatePlotProject_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Name 的本地化字符串。
        /// </summary>
        public static string CreatePlotProject_ProjectNameInput {
            get {
                return ResourceManager.GetString("CreatePlotProject_ProjectNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CreateNewPlotProject 的本地化字符串。
        /// </summary>
        public static string CreatePlotProject_WindowTitle {
            get {
                return ResourceManager.GetString("CreatePlotProject_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About MVPlot 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_AboutWindowTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input new condition (Fill it out with form) 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_ChangeConditionTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_ChangeConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert condition 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_ChangeConditionWindowTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_ChangeConditionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid condition form! 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_ConditionInvalid {
            get {
                return ResourceManager.GetString("MainEditWindow_ConditionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditions 的本地化字符串。
        /// </summary>
        public static string MainEditWIndow_Conditions {
            get {
                return ResourceManager.GetString("MainEditWIndow_Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure for deleting this plot? 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_DeletePlotAsk {
            get {
                return ResourceManager.GetString("MainEditWindow_DeletePlotAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing found. 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_FindNothing {
            get {
                return ResourceManager.GetString("MainEditWindow_FindNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search query 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_FindTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_FindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search next ... 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_FindWindowTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_FindWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action argument(Fill it out in the format) 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MainSender_ActionPlotRowContentTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_MainSender_ActionPlotRowContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action plot row 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MainSender_ActionPlotRowTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_MainSender_ActionPlotRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shake screen 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MainSender_ActionPlotRowType1 {
            get {
                return ResourceManager.GetString("MainEditWindow_MainSender_ActionPlotRowType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change BGM 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MainSender_ActionPlotRowType2 {
            get {
                return ResourceManager.GetString("MainEditWindow_MainSender_ActionPlotRowType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action type 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MainSender_ActionPlotRowTypeTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_MainSender_ActionPlotRowTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional arguments(File name) 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MainSender_AdditionalPlotRowContentTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_MainSender_AdditionalPlotRowContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional plot row 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MainSender_AdditionalPlotRowTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_MainSender_AdditionalPlotRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SE 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MainSender_AdditionalPlotRowType1 {
            get {
                return ResourceManager.GetString("MainEditWindow_MainSender_AdditionalPlotRowType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bubble 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MainSender_AdditionalPlotRowType2 {
            get {
                return ResourceManager.GetString("MainEditWindow_MainSender_AdditionalPlotRowType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Row type 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MainSender_AdditionalPlotRowTypeTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_MainSender_AdditionalPlotRowTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MainSender_NormalPlotRowContentTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_MainSender_NormalPlotRowContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character name (Empty for narrator row) 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MainSender_NormalPlotRowNameTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_MainSender_NormalPlotRowNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal plot row 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MainSender_NormalPlotRowTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_MainSender_NormalPlotRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Append 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MainSenderSend {
            get {
                return ResourceManager.GetString("MainEditWindow_MainSenderSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About MVPlot 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuAbout {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close current 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuClose {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuCopy {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create new 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuCreate {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create new plot 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuCreatePlot {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuCreatePlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuCut {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete condition 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuDeleteCondition {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuDeleteCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete current plot 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuDeletePlot {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuDeletePlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuEdit {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuExport {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to MVEdit 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuExportMVEdit {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuExportMVEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuFile {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find ... 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuFind {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find with regex... 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuFindRegex {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuFindRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuHelp {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert plot condition 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuInsertCondition {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuInsertCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open existing 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuOpen {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuPaste {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plot 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuPlot {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuRedo {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuSave {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select all 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuSelectAll {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuUndo {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usage 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_MenuUsage {
            get {
                return ResourceManager.GetString("MainEditWindow_MenuUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Plot 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_NewPlot {
            get {
                return ResourceManager.GetString("MainEditWindow_NewPlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Plot Yet.Press the button below to add one. 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_NoPlotHint {
            get {
                return ResourceManager.GetString("MainEditWindow_NoPlotHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste with append 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_AppendPaste {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_AppendPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_Copy {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy content 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_CopyContent {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_CopyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy row 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_CopyRow {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_CopyRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_Cut {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_Delete {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_Insert {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste with insert 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_InsertPaste {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_InsertPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_Move {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move backward 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_MoveBackward {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_MoveBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move backward to ... 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_MoveBackwardTo {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_MoveBackwardTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move forward 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_MoveForward {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_MoveForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move forward to ... 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_MoveForwardTo {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_MoveForwardTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiselect 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_Multiselect {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_Multiselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overwrite 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_Overwrite {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste with overwrite 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_OverwritePaste {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_OverwritePaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_PlotRowList_Paste {
            get {
                return ResourceManager.GetString("MainEditWindow_PlotRowList_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a plot at left to start. 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_SelectPlotHint {
            get {
                return ResourceManager.GetString("MainEditWindow_SelectPlotHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usage 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_UsageWindowTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_UsageWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plot Project - {0} 的本地化字符串。
        /// </summary>
        public static string MainEditWindow_WindowTitle {
            get {
                return ResourceManager.GetString("MainEditWindow_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a existing project 的本地化字符串。
        /// </summary>
        public static string OpenExisting {
            get {
                return ResourceManager.GetString("OpenExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target file exists.Would you like to overwrite it? 的本地化字符串。
        /// </summary>
        public static string PlotProjectCreation_CreateWarning {
            get {
                return ResourceManager.GetString("PlotProjectCreation_CreateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MV Plot Project(*.mpproj)|*.mpproj 的本地化字符串。
        /// </summary>
        public static string SelectFilter {
            get {
                return ResourceManager.GetString("SelectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a location to save 的本地化字符串。
        /// </summary>
        public static string SelectSaveLocation {
            get {
                return ResourceManager.GetString("SelectSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Project 的本地化字符串。
        /// </summary>
        public static string WelcomeWindow_NewProject {
            get {
                return ResourceManager.GetString("WelcomeWindow_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Project 的本地化字符串。
        /// </summary>
        public static string WelcomeWindow_OpenProject {
            get {
                return ResourceManager.GetString("WelcomeWindow_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MVPlot - A plot editor for the RPG Maker MV&apos;s games 的本地化字符串。
        /// </summary>
        public static string WelcomeWindow_Title {
            get {
                return ResourceManager.GetString("WelcomeWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to MVPlot 的本地化字符串。
        /// </summary>
        public static string WelcomeWindow_WindowTitle {
            get {
                return ResourceManager.GetString("WelcomeWindow_WindowTitle", resourceCulture);
            }
        }
    }
}
